core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mainapps.accounts.emails import (
    CustomPasswordResetConfirmView,
    CustomPasswordResetView,
)

urlpatterns = [
    path("", include("mainapps.home.urls", namespace="home")),
    path("admin/", admin.site.urls),
    path("accounts/", include("mainapps.accounts.urls", namespace="accounts")),
    path("video/", include("mainapps.video.urls", namespace="video")),
    path("text/", include("mainapps.vidoe_text.urls", namespace="video_text")),
    path(
        "auth/password_reset/", CustomPasswordResetView.as_view(), name="password_reset"
    ),
    path(
        "auth/reset/<uidb64>/<token>/",
        CustomPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path("auth/", include("django.contrib.auth.urls")),  # new
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapps/accounts/api/urls.py
urlpatterns = []

mainapps/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.login, name="signin"),
    path("logout/", views.logout_view, name="logout"),
    path("contact/", views.contact_view, name="contact"),
    path("verify/<str:token>", views.verify, name="verify"),
    path("stripe-webhook", views.stripe_webhook, name="stripe_webhook"),
    path("subscribe/<str:price_id>", views.subscribe, name="subscribe"),
    path("manage-subscription", views.manage_subscription, name="manage_subscription"),
    path(
        "upgrade-subscription/<str:price_id>",
        views.upgrade_subscription,
        name="upgrade_subscription",
    ),
    path(
        "downgrade-subscription",
        views.downgrade_subscription,
        name="downgrade_subscription",
    ),
    path("add-credits", views.add_credits, name="add_credits"),
    path("add-credits-success", views.add_credits_success, name="add_credits_success"),
    path("add-credits-cancel", views.add_credits_cancel, name="add_credits_cancel"),
    path("billing-portal", views.billing_portal, name="billing_portal"),
    path("cancel-subscription", views.cancel_subscription, name="cancel_subscription"),
]

mainapps/accounts/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models


class Plan(models.Model):
    stripe_price_id = models.CharField(max_length=255, null=True)
    name = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=5, decimal_places=2, null=True)
    price_per_vsl = models.DecimalField(max_digits=5, decimal_places=2, null=True)
    vsl_limit = models.IntegerField(default=0)

    class Meta:
        ordering = ['id'] 

class StripeCustomer(models.Model):
    user = models.ForeignKey("User", on_delete=models.CASCADE, null=True)
    stripe_customer_id = models.CharField(max_length=255)


class Subscription(models.Model):
    plan = models.ForeignKey(Plan, on_delete=models.CASCADE)
    stripe_subscription_id = models.CharField(max_length=255, null=True)
    customer = models.ForeignKey(StripeCustomer, on_delete=models.CASCADE, null=True)
    credits = models.IntegerField(default=0)
    current_period_end = models.IntegerField(default=0)


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("The Email field must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    # def create_superuser(self, email, password=None, **extra_fields):
    #     extra_fields.setdefault("is_staff", True)
    #     extra_fields.setdefault("is_superuser", True)
    #     return self.create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
            extra_fields.setdefault("is_staff", True)
            extra_fields.setdefault("is_superuser", True)

            if not extra_fields.get("is_staff"):
                raise ValueError("Superuser must have is_staff=True.")
            if not extra_fields.get("is_superuser"):
                raise ValueError("Superuser must have is_superuser=True.")

            user = self.create_user(email, password, **extra_fields)

            try:
                admin_plan = Plan.objects.get(id=4) 
                stripe_customer = StripeCustomer.objects.create(user=user, stripe_customer_id=f"admin_{user.id}")
                subscription = Subscription.objects.create(
                    plan=admin_plan,
                    stripe_subscription_id=f"sub_admin_{user.id}",
                    customer=stripe_customer,
                    credits=admin_plan.vsl_limit,  
                )

                user.subscription = subscription
                user.save()
            except Plan.DoesNotExist:
                return user
                # raise ValueError("Admin plan with ID=4 does not exist. Please create it first.")


            return user

class User(AbstractUser):
    email = models.EmailField(unique=True, null=False, blank=False)
    api_key = models.CharField(max_length=255, blank=True, null=True)
    verification_token = models.CharField(max_length=100, blank=True, null=True)
    subscription = models.ForeignKey(Subscription, on_delete=models.SET_NULL, null=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def save(self, *args, **kwargs):
        self.username = self.email
        super().save(*args, **kwargs)

    def can_generate_video(self):
        return self.subscription.credits >= 1

mainapps/accounts/views.py
from datetime import datetime
from django.shortcuts import render, redirect
from django.contrib.auth import (
    authenticate,
    login as auth_login,
    logout,
    get_user_model,
)
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse, HttpResponse
from mainapps.accounts.emails import send_html_email2
from django.conf import settings
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.core.mail import send_mail
from .models import Plan, Subscription, StripeCustomer
import stripe
import uuid


@csrf_exempt
def contact_view(request):
    if request.method == "POST":
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        email = request.POST.get("email")
        message = request.POST.get("message")

        subject = f"New Contact Form Submission from {first_name} {last_name}"
        email_body = f"First Name: {first_name}\nLast Name: {last_name}\nEmail: {email}\nMessage:\n{message}"

        try:
            send_mail(
                subject,
                email_body,
                settings.DEFAULT_FROM_EMAIL,
                [
                    settings.DEFAULT_FROM_EMAIL,
                ],
            )
            return JsonResponse(
                {"success": True, "message": "Your message has been sent successfully!"}
            )
        except Exception as e:
            return JsonResponse(
                {"success": False, "message": f"An error occurred: {str(e)}"}
            )

    return JsonResponse({"success": False, "message": "Invalid request method."})


def logout_view(request):
    logout(request)

    # messages.success(request, "You Have Been Successfully Logged Out.")

    return redirect("/")


def login(request):
    if request.user.is_authenticated:
        return redirect("/text")

    if request.method == "POST":
        email = request.POST["email"]
        password = request.POST["password"]

        user = authenticate(request, username=email, password=password)

        if user is not None:
            if user.verification_token is None:
                auth_login(request, user)

                try:
                    return redirect(request.session.get("next"))
                except:
                    return redirect("/text")
            else:
                messages.error(
                    request,
                    "Your Email Address Is Not Verified. Please Verify Your Email Before Logging In.",
                )
        else:
            messages.error(request, "Invalid Username or Password. Please Try Again.")

    next = request.GET.get("next", "")
    request.session["next"] = next
    return render(
        request,
        "accounts/login.html",
    )


def register(request):
    if request.method == "POST":
        stripe.api_key = settings.STRIPE_SEC_KEY

        checkout_session_id = request.POST.get("session_id")

        name = request.POST.get("name")
        email = request.POST.get("email")
        password1 = request.POST.get("password1")
        password2 = request.POST.get("password2")

        if len(password1) < 6:
            messages.error(request, "At Least 6 Characters Are Required")
            return render(
                request,
                "accounts/register.html",
                context={"session_id": checkout_session_id},
            )

        if password1 != password2:
            messages.error(request, "Passwords Do Not Match.")
            return render(
                request,
                "accounts/register.html",
                context={"session_id": checkout_session_id},
            )

        User = get_user_model()
        if User.objects.filter(email=email).exists():
            messages.error(request, "This Email Is Already Registered.")
            return render(
                request,
                "accounts/register.html",
                context={"session_id": checkout_session_id},
            )

        user = User.objects.create_user(email=email, password=password1)
        user.first_name = name
        user.save()

        if checkout_session_id is None:
            free_plan = Plan.objects.get(id=3)
            customer = stripe.Customer.create(
                email=user.email,
                name=user.first_name,
            )
            stripe_customer = StripeCustomer(user=user, stripe_customer_id=customer.id)
            stripe_customer.save()
            subscription = Subscription(
                plan=free_plan,
                credits=1,
                customer=stripe_customer,
                stripe_subscription_id=None,
            )
            subscription.save()
            user.subscription = subscription

            verification_token = str(uuid.uuid4())
            user.verification_token = verification_token

            user.save()

            send_html_email2(
                subject="Welcome to VideoCrafter.io – Verify Your Email To Continue",
                message=None,
                from_email=settings.DEFAULT_FROM_EMAIL,
                to_email=user.email,
                html_file="accounts/verification.html",
                context={
                    "first_name": user.first_name,
                    "verification_url": settings.DOMAIN_NAME
                    + reverse("accounts:verify", kwargs={"token": verification_token}),
                },
            )

            return render(
                request,
                "accounts/register.html",
                context={"price_id": "free", "success": True},
            )

        else:
            checkout_session = stripe.checkout.Session.retrieve(checkout_session_id)
            stripe_customer_id = checkout_session.customer
            subscription_id = checkout_session.get("subscription")
            if subscription_id:
                subscription = stripe.Subscription.retrieve(subscription_id)
                price_id = subscription["items"]["data"][0]["price"]["id"]
                print("Price ID:", price_id)
                customer_id = 0
                plan=Plan.objects.get(stripe_price_id=price_id)
                try:
                    customer = StripeCustomer.objects.get(
                        stripe_customer_id=stripe_customer_id
                    )

                    if customer is not None:
                        customer.user = user
                        customer.save()

                        customer_id = customer.id
                except StripeCustomer.DoesNotExist:
                    new_customer = StripeCustomer(
                        user=user, stripe_customer_id=stripe_customer_id
                    )
                    new_customer.save()

                    customer_id = new_customer.id

                try:

                    subscription = Subscription.objects.create(
                    plan=plan,
                    credits=plan.vsl_limit,
                    customer=new_customer,
                    stripe_subscription_id=subscription_id,
                    )   
                    user.subscription = subscription
                    user.save()

                except Exception as _:
                    messages.error(request, f"Subscription Failed. Please Try Again Later. {_}")
                    return redirect(f'/accounts/register/?session_id={checkout_session_id}'
                    )

            send_html_email2(
                subject="Welcome to VideoCrafter.io",
                message=None,
                from_email=settings.DEFAULT_FROM_EMAIL,
                to_email=user.email,
                html_file="accounts/welcome.html",
                context={
                    "user_name": user.first_name,
                    "login_url": settings.DOMAIN_NAME + reverse("video_text:add_text"),
                },
            )

            auth_login(request, user)
            return redirect(reverse("video_text:add_text"))
    
    elif request.method == "GET":
        checkout_session_id = request.GET.get("session_id")

        return render(
            request,
            "accounts/register.html",
            context={"session_id": checkout_session_id},
        )


def verify(request, token):
    try:
        user = get_user_model().objects.get(verification_token=token)

        if user is not None:
            user.verification_token = None
            user.save()

            auth_login(request, user)
            return redirect("video_text:add_text")
    except:
        return redirect(reverse("home:home"))


@csrf_exempt
def stripe_webhook(request):
    stripe.api_key = settings.STRIPE_SEC_KEY

    endpoint_secret = settings.STRIPE_ENDPOINT_SECRET
    payload = request.body
    sig_header = request.META["HTTP_STRIPE_SIGNATURE"]

    event = None
    try:
        event = stripe.Webhook.construct_event(payload, sig_header, endpoint_secret)
    except ValueError as _:
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError as _:
        return HttpResponse(status=400)

    event_type = event["type"]
    event_object = event["data"]["object"]

    if event_type == "invoice.payment_succeeded":
        if event_object.billing_reason == "subscription_create":
            try:
                customer_id = event_object.customer

                customer = None
                try:
                    customer = StripeCustomer.objects.get(
                        stripe_customer_id=customer_id
                    )
                except StripeCustomer.DoesNotExist:
                    customer = StripeCustomer(user=None, stripe_customer_id=customer_id)
                    customer.save()

                prev_sub = None
                prev_sub_credits = 0
                try:
                    prev_sub = Subscription.objects.get(customer_id=customer.id)

                    if prev_sub is not None:

templates/accounts/base.html
<!-- base.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    {%include 'partials/head_c.html' %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
    <style>

.container {
    width: 100%;
    max-width: 400px;
    margin: 50px auto;
    background: white;
    border-radius: 5px;
    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
    padding: 20px;
}

h2 {
    text-align: center;
    color: #333;
}

.form-group {
    margin-bottom: 15px;
}

label {
    display: block;
    margin-bottom: 5px;
    color: #555;
}

input[type="text"],
input[type="email"],
input[type="password"] {
    width: 100%;
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 3px;
}

button {
    width: 100%;
    padding: 10px;
    background-color: #864af9;
    color: white;
    border: none;
    border-radius: 3px;
    cursor: pointer;
}

button:hover {
    background-color: #864af9;
}

.alert {
    color: red;
    text-align: center;
}

    </style>
</head>
<body>
    {% block content %}

    {% endblock %}
</body>
</html>

templates/accounts/details.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    {% include 'partials/head_c.html' %}

    <link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />

    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Plus+Jakarta+Sans:ital,wght@0,200..800;1,200..800&display=swap"
          rel="stylesheet" />

    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" />

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous" />

    <link rel="stylesheet"
          type="text/css"
          href="{% static 'accounts/transaction.css' %}"
          media="screen" />
    <link rel="stylesheet"
          type="text/css"
          href="{% static 'accounts/transaction-responsiveness.css' %}"
          media="screen" />

    <style>
      a {
        text-decoration: none;
        color: #000000;
      }

      p {
        padding: 0;
        margin: 0;
 
  text-transform:capitalise;
 
      }

      .outer {
        max-width: 65%;
        margin: 3rem auto 0 auto;
        font-family: 'Montserrat';
      }

      .info-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        border-radius: 8px 8px 0 0;
        border: 2px solid rgba(0, 0, 0, 0.171);
        padding: 1.6rem;
      }

      .info-header h3 {
        padding: 0;
        margin: 0;
      }

      .info-header a {
        border: 2px solid rgba(0, 0, 0, 0.171);
        border-radius: 25px;
        padding: 10px 15px;
        text-decoration: none;
        transition: all ease-out 0.2s;
        font-size: 17px;
        font-weight: 500;
      }

      .info-header a:hover {
        background-color: #864AF9;
        color: #ffffff;
        border: 2px solid #864AF9;
      }

      .inner {
        border-right: 2px solid rgba(0, 0, 0, 0.171);
        border-bottom: 2px solid rgba(0, 0, 0, 0.171);
        border-left: 2px solid rgba(0, 0, 0, 0.171);
        border-radius: 0 0 8px 8px;
        padding: 0 30px;
      }

      .section {
        border-bottom: 2px solid rgba(0, 0, 0, 0.171);
        padding: 30px 0;
        display: flex;
        align-items: center;
        gap: 20px;
      }

      .section:last-child {
        border-bottom: none;
      }

      .section>p:first-of-type {
        font-weight: 600;
      }

      .section p {
        font-size: 18px;
      }

      .btn {
        background-color: #cbcbcb;
        text-transform: capitalize;
      }

      .active {
        background-color: #41FF714D;
      }

      .btn,
      .active {
        border-radius: 25px;
        padding: 10px 15px;
        font-weight: 600;
        font-size: 16px;
      }

      .section:last-child {
        display: block;
      }

      .credit-header {
        margin-bottom: 25px;
      }

      .credit-info {
        display: flex;
        justify-content: space-between;
        color: #747474;
      }

      .second-main p {
        text-align: center;
      }

      .credit-box {
        padding: 35px;
      }

      .cr {
        margin-bottom: 23px;
      }

      .cr+p {
        margin-bottom: 15px;
      }

      .credit-box {
        border-radius: 7px;
      }

      .box-cont input {
        padding: 17px 25px;
        border-radius: 7px;
      }

      .credit-box button {
        padding: 17px 25px;
        border: none;
        border-radius: 7px;
      }

      .plans {
        gap: 2rem;
        grid-template-columns: repeat(2, 1fr);
        width: 50%;
      }

      .box {
        border-radius: 8px;
      }

      .box-head {
        margin-bottom: 20px;
        text-transform: capitalize;
      }

      .box p {
        margin-bottom: 17px;
      }

      .box a {
        margin: 20px 0 0 0;
        width: 100%;
        color: #000;
        background-color: #fff;
        text-transform: capitalize;
        font-weight: bold;
        margin-bottom: 0.67rem;
        font-weight: 500;
        text-align: center;
        margin: 0;
        border: 1px solid #000;
        border-radius: 9px;
        padding: 8px;
        cursor: pointer;
        font-size: 19px;
        transition: all ease-out 0.2s;
        display: block;
      }

      .box button {
        margin-bottom: 0;
      }

      .box a:hover {
        border: none;
        background-color: #5f12d1;
        border: 1px solid #5f12d1;
        color: white;
      }

      #up {
        border: 1px solid #893BFF;
      }

      .second-main {
        margin-top: 3rem;
      }

      .credit-box button[disabled] {
        background-color: #c4c4c4;
      }

      .cancel-sub-overlay {
        position: fixed;
        background-color: #00000077;
        z-index: 99999;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
        display: flex;
        justify-content: center;
        align-items: center;
      }

      .cancel-sub-popup {
        width: 27%;
        background-color: #ffffff;
        padding: 32px 32px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1), 0 6px 20px rgba(0, 0, 0, 0.1);
        border-radius: 8px;
        text-align: center;
        text-transform: capitalize;
      }

      .cancel-sub-heading {
        color: #864AF9;
        font-size: 20px;
        margin-bottom: 35px;
      }

      .cancel-sub-msg {
        font-size: 17px;
        margin-bottom: 35px;
      }

      .cancel-sub-choices {
        display: flex;
        justify-content: space-between;
        width: 50%;
        margin: 0 auto;
      }

      .cancel-sub-choices button {
        border: 2px solid #893bff;
        background-color: #893bff;
        border-radius: 10px;
        padding: 13px 25px;
        cursor: pointer;
        font-size: 17px;
        transition: all ease-out 0.2s;
        display: block;
        color: #ffffff;
      }

      .cancel-sub-choices a {
        transition: all ease-out 0.2s;
        display: block;
        cursor: pointer;
        font-size: 17px;
        border-radius: 10px;
        padding: 13px 25px;
        text-decoration: none;
        border: 2px solid #000000;
      }

      .cancel-sub-choices a:hover {
        border: 2px solid #893bff;
        background-color: #893bff;
        color: #ffffff;
      }

      .cancel-sub-choices button:hover {
        background-color: #5f12d1;
        border: 2px solid #5f12d1;
      }

      .hidden {
        display: none;
      }

      @media (max-width: 1356px) {
        .plans {
         
          grid-template-columns: 1fr;
          
        }
    }


      
    </style>
  </head>
  <body>
    {% include 'sub_header.html' %}

    {% include 'messages.html' %}

    <div class="outer">
      <div class="info-header">
        <h3>Subscription Details</h3>
        <a href="billing-portal">Manage Billing Info</a>
      </div>

      <div class="inner">
        <div class="section">
          <p>Current Plan:</p>
          <p class="btn">{{ cur_plan.name }}</p>
        </div>

        <div class="section">
          <p>Subscription Status:</p>
          {% if cur_plan.name|lower == 'free'  %}
            <p class="btn">Trial</p>
            {% elif  cur_plan.name|lower == 'cancelled'%}
            <p class="btn">Not Active</p>
          {% else %}
            <p class="active">Active</p>
          {% endif %}
        </div>

        <div class="section">
          <p class="credit-header">Credit Usage</p>
          <div class="credit-info">
            {% if   cur_plan.name|lower == 'free' or  cur_plan.name|lower == 'cancelled' %}
            <p>You currently do not have an active plan.</p>
            <p>Unused credits will expire in  {{days_left}} Days </p>
            {%else%}
            <p>Any unused credit will roll over to the next month</p>
            <p>Next recharge in {{days_left}} Days </p>
            {% endif %}
          </div>
        </div>
      </div>
    </div>

    <div class="second-main">
      <div class="heading">Need More Credits?</div>
      <p>
        Out of VSL edits? No worries! Add more edits to your account instantly.
        Choose the number of extra edits you need, with a minimum of 5,
        and keep creating high-converting VSLs without delays.
      </p>

    </div>

    <div class="credit-box">
      <div class="box-cont">
        <form action="{% url 'accounts:add_credits' %}" method="post">
          {% csrf_token %}
          <p class="cr">Buy More Credits</p>
          <p>${{ cur_plan.price_per_vsl }} Each</p>
          <input type="number"
                 min="1"
                 name="credits_number"
                 id="credit"
                 required
                 placeholder="Enter the amount of credits" />
          <button type="submit"
                  {% if cur_plan.name|lower == 'free' or  cur_plan.name|lower == 'cancelled' %}disabled{% endif %}>Buy</button>
        </form>
      </div>
    </div>

    <div class="main-head">
      <h1>Plans that scale with your business</h1>
    </div>

    <div class="plans">
      <div class="box">
        <p class="box-head">{{ plans.0.name }} Plan</p>
        <p id="p">Perfect for scaling your video advertising campaigns</p>
        <br>
        <div class="price">
          <h1>${{ plans.0.price }}</h1>
          <span>/Month</span>
        </div>
        <p id="p">Just ${{ plans.0.price_per_vsl }} per Videos</p>
        <p id="p" style="min-height: 70px;">
          <i class="fa-solid fa-check"></i> Create up to {{ plans.0.vsl_limit }} Videos per month
        </p>

        {% if cur_plan.name|lower == 'growth' %}
          <button type="button" class="cancel_button" id="up">
            Cancel Subscription
          </button>
        {% elif cur_plan.name|lower == 'free' or cur_plan.name|lower == 'cancelled' %}
          <a href="{% url 'accounts:upgrade_subscription' price_id=plans.0.stripe_price_id %}?success_path=/accounts/manage-subscription&cancel_path=/accounts/manage-subscription">Upgrade Subscription</a>
        {% else %}
          <button type="button" id="downgradeButton">Downgrade Subscription</button>
        {% endif %}
      </a>
    </div>

    <div class="box">
      <p class="box-head">{{ plans.1.name }} Plan</p>
      <p id="p">Ideal for high-volume marketers and agencies</p>
      <br />
      <div class="price">
        <h1>${{ plans.1.price }}</h1>
        <span>/Month</span>
      </div>
      <p id="p">Just ${{ plans.1.price_per_vsl }} per Videos</p>
      <p id="p" style="min-height: 70px;">
        <i class="fa-solid fa-check"></i> Create up to {{ plans.1.vsl_limit }} Videos per month
      </p>
      {% if cur_plan.name|lower == 'pro' %}
        <button type="button" class="cancel_button" id="up">
          Cancel Subscription
        </button>
      {% else %}
        <a href="{% url 'accounts:upgrade_subscription' price_id=plans.1.stripe_price_id %}?success_path=/accounts/manage-subscription&cancel_path=/accounts/manage-subscription">Upgrade Subscription</a>
      {% endif %}
    </div>
  </div>

  <div class="cancel-sub-overlay hidden" id="cancelOverlay">
    <div class="cancel-sub-popup">
      <p class="cancel-sub-heading">Cancel Subscription?</p>
      <p class="cancel-sub-msg">
        Are you sure you want to cancel your subscription?
      </p>
      <div class="cancel-sub-choices">
        <button id="cancelSubPopupNoBtn" type="button">No</button>
        <a href="{% url 'accounts:cancel_subscription' %}">Yes</a>
      </div>
    </div>
  </div>

  <div class="cancel-sub-overlay hidden" id="downgradeOverlay">
    <div class="cancel-sub-popup">
      <p class="cancel-sub-heading">Downgrade Subscription?</p>
      <p class="cancel-sub-msg">
        Are you sure you want to downgrade your subscription?
      </p>
      <div class="cancel-sub-choices">
        <button id="downgradeSubPopupNoBtn" type="button">No</button>
        <a href="{% url 'accounts:downgrade_subscription' %}?success_path=/accounts/manage-subscription&cancel_path=/accounts/manage-subscription">Yes</a>
      </div>
    </div>
  </div>

  <script>
    document.querySelector('.cancel_button').addEventListener('click', () => {
      document.querySelector('#cancelOverlay').classList.remove('hidden');
    });

    document.querySelector('#cancelSubPopupNoBtn').addEventListener('click', () => {
      document.querySelector('#cancelOverlay').classList.add('hidden');
    });

    document.querySelector('#downgradeButton').addEventListener('click', () => {
      document.querySelector('#downgradeOverlay').classList.remove('hidden');
    });

    document.querySelector('#downgradeSubPopupNoBtn').addEventListener('click', () => {
      document.querySelector('#downgradeOverlay').classList.add('hidden');
    });
  </script>
</body>
</html>

templates/accounts/password_reset_complete.html
{%extends 'accounts/base.html' %}
{% block content %}
<div class="container">
  <h2>Password Reset Complete</h2>
  <p>Your password has been successfully changed. You can now <a href="{% url 'accounts:login' %}">log in</a>.</p>
</div>
{% endblock %}

templates/accounts/password_reset_confirm.html
{%extends 'accounts/base.html' %}
{% block content %}

<div class="container">
  <h2>Enter New Password</h2>
    <form method="post" action="{% url 'accounts:password_reset_confirm' uid token %}" >
        {% csrf_token %}
        <div class="form-group">
            {{ form.new_password1.label }}
            {{ form.new_password1 }}
            {% for error in form.new_password1.errors %}
                <div class="alert">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="form-group">
            {{ form.new_password2.label }}
            {{ form.new_password2 }}
            {% for error in form.new_password2.errors %}
                <div class="alert">{{ error }}</div>
            {% endfor %}
        </div>
        <button type="submit">Change Password</button>
      </form>
    </div>
    
    {% endblock content %}

templates/accounts/password_reset_done.html
{%extends 'accounts/base.html' %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">

<div class="container">
    <h2>Password Reset Sent</h2>
    <p>A link to reset your password has been sent to your email.</p>
</div>

{% endblock content %}