core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mainapps.accounts.emails import (
    CustomPasswordResetConfirmView,
    CustomPasswordResetView,
)

urlpatterns = [
    path("", include("mainapps.home.urls", namespace="home")),
    path("admin/", admin.site.urls),
    path("accounts/", include("mainapps.accounts.urls", namespace="accounts")),
    path("video/", include("mainapps.video.urls", namespace="video")),
    path("text/", include("mainapps.vidoe_text.urls", namespace="video_text")),
    path(
        "auth/password_reset/", CustomPasswordResetView.as_view(), name="password_reset"
    ),
    path(
        "auth/reset/<uidb64>/<token>/",
        CustomPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path("auth/", include("django.contrib.auth.urls")),  # new
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapps/vidoe_text/urls.py
from django.urls import path
from . import views
from django.urls import re_path

app_name = "video_text"
urlpatterns = [
    path("", views.add_text, name="add_text"),
    path(
        "process-textfile/<str:textfile_id>/", views.process_textfile, name="process_textfile"
    ),
    path("get_clips_id/<str:textfile_id>/", views.get_clips_id, name="get_clips_id"),
    path("download_video/<str:textfile_id>/", views.download_video, name="download_video"),
    path(
        "progress_page/<str:al_the_way>/<str:text_file_id>",
        views.progress_page,
        name="progress_page",
    ),
    path('check-subtitles/<int:text_file_id>/', views.check_subtitles_length, name='check_subtitles_length'),
    path("update-subtitle-positions/", views.update_subtitle_positions, name="update_subtitle_positions"),
    path("add_text_clip_line/<str:textfile_id>/", views.add_text_clip_line, name="add_text_clip_line"),
    path("edit_text_clip_line/<str:id>/", views.edit_text_clip_line, name="edit_text_clip_line"),
    path(
        "delete-clip/<int:id>/",
        views.delete_clip,
        name="delete_clip",
    ),
    path("progress/<str:text_file_id>/", views.progress, name="progress"),
    path("add_subclip/<str:id>/", views.add_subclip, name="add_subclip"),
    path("edit_subcliphtmx/<str:id>/", views.edit_subcliphtmx, name="edit_subcliphtmx"),
    path("add_subcliphtmx/<str:id>/", views.add_subcliphtmx, name="add_subcliphtmx"),
    path("reset_subclip/<str:id>/", views.reset_subclip , name="reset_subclip"),
    path("edit_subclip/<str:id>/", views.edit_subclip, name="edit_subclip"),
    path("check_text_clip/<str:textfile_id>/", views.check_text_clip, name="check_text_clip"),
    path("delete_textfile/<str:textfile_id>/", views.delete_textfile, name="delete_textfile"),
    path("update_textfile/<str:textfile_id>/", views.update_textfile, name="update_textfile"),
    path(
        "process-background-music/<str:textfile_id>/",
        views.process_background_music,
        name="process_background_music",
    ),
    path("media/<str:file_name>/", views.serve_file, name="serve_file"),
    re_path(
        r"^media/(?P<file_key>.+)/(?P<textfile_id>\w+)/$",
        views.download_file_from_s3,
        name="download_file",
    ),
    re_path(r"^media/(?P<file_key>.+)/$", views.download_file_from_s3, name="download_file_"),
    path(
        "delete-background-music/<int:id>/",
        views.delete_background_music,
        name="delete_background_music",
    ),
    path("manage_textfile/", views.manage_textfile, name="manage_textfile"),
    path("validate_api_key/", views.validate_api_keyv, name="validate_api_key"),
]

templates/assets/assets.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {%include 'partials/head_c.html' %}

<style>
   
    a {
    text-decoration: none; 
    color: inherit;        
    outline: none; 
    display: flex;     
    align-items:center;
    cursor: pointer;
}
.newFolder:hover,.newVideo:hover{
  background-color: #00000010;

}
.loader {
display: none;
position: fixed;
z-index: 9999;
top: 50%;
left: 50%;
transform: translate(-50%, -50%);
width: 50px;
height: 50px;
border: 5px solid #f3f3f3;
border-top: 5px solid #9662f9;
border-radius: 50%;
animation: spin 1s linear infinite;
}

@keyframes spin {
0% { transform: rotate(0deg); }
100% { transform: rotate(360deg); }
}
/* Centered video card */
.video-card {
/* width: 80%; Adjust as per your need */
max-width: 400px; /* To restrict excessive width on large screens */
padding: 20px;
border-radius: 10px;
background-color: #f2f2f2; /* Ash color */
box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
display: flex;
justify-content: center;
align-items: center;
flex-direction: column;
}
.actions{
display:none
}


</style>
    
</head>
<body>
<div class="loader"></div>
    {% include 'sub_header.html' %}
{% include 'messages.html'%}

<div id="confirmation-box"></div>
{% if not category_id %}
{% include 'assets/vcl/folder1/folder1.html' %}
{% elif  category_id and not video_id %}
{% include 'assets/vcl/folder2/folder2.html' %}
{% elif  category_id and video_id %}
{% include 'assets/vcl/folder3/folder3.html' %}
{% endif %}
<script src="{% static 'htmx.js' %}"></script>

<script src="{% static 'resources/assets.js' %}"></script>
    
</body>
</html> 

templates/assets/text_files.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {%include 'partials/head_c.html' %}
    
<style>
   body {

font-size: 1.0rem!important;

}


.box > div:first-child {

font-size: 1.0rem!important;

}

.box > .log > div {

font-size: 1.0rem!important;
}

.log > div > .actions > div {
font-size: 0.9rem!important;

}

.box > div > .newFolder {
font-size: 1.0rem!important;

}
    a {
    text-decoration: none; 
    color: inherit;        
    outline: none; 
    display: flex;     
    align-items:center;
    cursor: pointer;
}
.newFolder:hover,.newVideo:hover{
  background-color: #00000010;

}
.loader {
display: none;
position: fixed;
z-index: 9999;
top: 50%;
left: 50%;
transform: translate(-50%, -50%);
width: 50px;
height: 50px;
border: 5px solid #f3f3f3;
border-top: 5px solid #9662f9;
border-radius: 50%;
animation: spin 1s linear infinite;
}

@keyframes spin {
0% { transform: rotate(0deg); }
100% { transform: rotate(360deg); }
}
/* Centered video card */
.video-card {
/* width: 80%; Adjust as per your need */
max-width: 400px; /* To restrict excessive width on large screens */
padding: 20px;
border-radius: 10px;
background-color: #f2f2f2; /* Ash color */
box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
display: flex;
justify-content: center;
align-items: center;
flex-direction: column;
}
.actions{
display:none
}


</style>
    
</head>
<body>
<div class="loader"></div>
    {% include 'sub_header.html' %}
{% include 'messages.html'%}




    <link rel="stylesheet" href="{% static 'resources/assets/folder1.css' %}">

    <style>
        
    </style>

    <div class="content">
        <div class="box">
            <div>
                <div class="folderpath">
                    <a >Recently Processed Videos</a>
                    <!-- <img src="{% static 'resources/assets/assets1/Chevron-down.svg' %}" alt=""> -->
                </div>
                <div class="newFolder" style="padding:8px">
                    
                    <!-- <a > 
                        <img src="{% static 'resources/assets/assets1/create.svg' %}" alt="">
                        <span  style="padding-left: 5px;">Import Folder</span> 
                    </a> -->
                </div>
            </div>
            <div class="log">
                <div>
                    <div>
                        <input type="checkbox" name="selectall" id="" style="opacity:0;">
                        <div>Text Files</div>
                    </div>
                    <div>Clips</div>
                    <div>Created At</div>
                </div>
                {% for textfile in textfiles %}
                <div>
                    
                    <div>
                        <input type="checkbox" name="selectall" id=""style="opacity:0;">
                        <div>
                            
                            <a href="{%url 'video_text:download_video' textfile.id %}">
                                {{textfile.file_text}}
                            </a>
                        </div>
                    </div>
                    <div>{{textfile.clip_number}}</div>
                    <div>{{textfile.created_at }}</div>
                    <img src="{% static 'resources/assets/assets1/dots.svg' %}"class="menu" alt="">
                    <div class="actions">
                        <div>
                            <a hx-get="{% url 'video_text:delete_textfile' textfile.id %}"  hx-target="#confirmation-box" 
                            hx-swap="innerHTML">
                                <img src="{% static 'resources/assets/assets1/rename.svg' %}" alt="">
                                Delete
                            </a>
                        </div>
                       
                    </div>
                </div>
                {% endfor %}

            </div>

        </div>
    </div>

    

    <div id="confirmation-box"></div>


<script src="{% static 'htmx.js' %}"></script>

<script src="{% static 'resources/assets.js' %}"></script>
    
</body>
</html> 