core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mainapps.accounts.emails import (
    CustomPasswordResetConfirmView,
    CustomPasswordResetView,
)

urlpatterns = [
    path("", include("mainapps.home.urls", namespace="home")),
    path("admin/", admin.site.urls),
    path("accounts/", include("mainapps.accounts.urls", namespace="accounts")),
    path("video/", include("mainapps.video.urls", namespace="video")),
    path("text/", include("mainapps.vidoe_text.urls", namespace="video_text")),
    path(
        "auth/password_reset/", CustomPasswordResetView.as_view(), name="password_reset"
    ),
    path(
        "auth/reset/<uidb64>/<token>/",
        CustomPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path("auth/", include("django.contrib.auth.urls")),  # new
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapps/video/urls.py
from django.urls import path
from . import views

app_name = "video"
urlpatterns = [
    path("add-scene/<str:textfile_id>/", views.add_video_clips, name="add_scenes"),
    path("get_clip/<str:cat_id>/", views.get_clip, name="get_clip"),
    path("upload-folder/", views.upload_video_folder, name="upload_video_folder"),
    path("assets/<str:category_id>/", views.category_view, name="subcategory_view"),
    path("assets/", views.category_view, name="category_view"),
    path(
        "assets/<str:category_id>/<str:video_id>/",
        views.category_view,
        name="category_view_video",
    ),
    path('speed-up-video/', views.speed_up_video, name='speed_up_video'),
    path('api/video-categories/', views.fetch_video_categories, name='fetch_video_categories'),
    path(
        "categories/delete/<int:category_id>/",
        views.delete_category,
        name="delete_category",
    ),

    path("clips/delete/<int:clip_id>/", views.delete_clip, name="delete_video"),
    path(
        "add-video-clip/<int:category_id>/", views.add_video_clip, name="add_video_clip"
    ),
    path(
        "rename-video-clip/<int:video_id>/",
        views.rename_video_clip,
        name="rename_video_clip",
    ),
    path("rename-folder/<int:category_id>/", views.rename_folder, name="rename_folder"),
]

templates/assets/vcl/folder1/folder1.html
{% load static %}

    <link rel="stylesheet" href="{% static 'resources/assets/folder1.css' %}">

    <style>
        body {

            font-size: 1.0rem!important;
            
        }
        
        
        .box > div:first-child {

            font-size: 1.0rem!important;
  
        }
        
        .box > .log > div {

            font-size: 1.0rem!important;
        }
        
        .log > div > .actions > div {
            font-size: 0.9rem!important;
     
        }

        .box > div > .newFolder {
            font-size: 1.0rem!important;
          
        }
    </style>

    <div class="content">
        <div class="box">
            <div>
                <div class="folderpath">
                    <a href="{%url 'video:category_view' %}">Assets Library</a>
                    <img src="{% static 'resources/assets/assets1/Chevron-down.svg' %}" alt="">
                </div>
                <div class="newFolder" style="padding:8px">
                    
                    <a hx-get="{% url 'video:upload_video_folder' %}"  hx-target="#confirmation-box" 
                        hx-swap="innerHTML"> 
                        <img src="{% static 'resources/assets/assets1/create.svg' %}" alt="">
                        <span  style="padding-left: 5px;">Import Folder</span> 
                    </a>
                </div>
            </div>
            <div class="log">
                <div>
                    <div>
                        <input type="checkbox" name="selectall" id="" style="opacity:0;">
                        <div>Folder Name</div>
                    </div>
                    <div>Items</div>
                    <div>Modified At</div>
                </div>
                {% for folder in folders %}
                <div>
                    
                    <div>
                        <input type="checkbox" name="selectall" id=""style="opacity:0;">
                        <div>
                            
                            <a href="{%url 'video:subcategory_view' folder.id %}">
                                {{folder.name}}
                            </a>
                        </div>
                    </div>
                    <div>{{folder.get_clip_number}}</div>
                    <div>{{folder.updated_at }}</div>
                    <img src="{% static 'resources/assets/assets1/dots.svg' %}"class="menu" alt="">
                    <div class="actions">
                        <div>
                            <a hx-get="{% url 'video:rename_folder' folder.id %}"  hx-target="#confirmation-box" 
                            hx-swap="innerHTML">
                                <img src="{% static 'resources/assets/assets1/rename.svg' %}" alt="">
                                Rename
                            </a>
                        </div>
                        <div>
                            <a hx-get="{% url 'video:delete_category' folder.id %}"  hx-target="#confirmation-box" 
                            hx-swap="innerHTML">
                                <img src="{% static 'resources/assets/assets1/delete.svg' %}" alt="">
                                Delete
                            </a> 


                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>

        </div>
    </div>

    
    <!-- <script src="{% static 'resources/assets/folder.js' %}"></script> -->